<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-02-18 14:23
=======
# Generated by Django 4.1.7 on 2023-02-18 13:48
>>>>>>> 14c692bad7bea83d50b6c2bbeef94fb1fc87fe22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsmodel',
            old_name='users',
            new_name='user',
        ),
    ]
