# Generated by Django 4.1.7 on 2023-02-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_studentsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teachersmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='teachersmodel',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='nickname',
        ),
        migrations.CreateModel(
            name='ProfilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
