# Generated by Django 4.1.7 on 2023-02-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_categorymodel_coursesmodel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='CategoriesModel',
        ),
    ]
